version: "3.8"
services:

  geth:
    container_name: geth
    build:
      context: ./geth
      dockerfile: Dockerfile
    ports:
      - "8545:8545"
      - "8546:8546"
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ./geth/node:/geth

  tx-creation:
    container_name: tx-creation
    build:
      context: ./approach1/tx-creation
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - TZ=Europe/Berlin
      - PORT=8080
      - PRIVATE_KEY=bcc6d4aa1e277f085b3e11f2c1e6f14dd04e8108c823898e06fa5287c2bf1a92
      - NODE_URL=ws://geth:8546
      - CONTRACT_ADDRESS=0x17cB057648a03dE335c773C7F6b7719c63A32eB7

  tx-requesting:
    container_name: tx-requesting
    build:
      context: ./approach1/tx-requests
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    environment:
      - TZ=Europe/Berlin
      - PORT=8090
      - REQUEST_INTERVAL=250
      - TX_CREATION_MACHINE_URL=http://tx-creation:8080