version: "3.8"
services:

  test-service:
    image: 127.0.0.1:5000/test-service
    build:
      context: ./performance-test
      dockerfile: Dockerfile
    command:
      - "45"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5"