version: "3.8"
services:

  geth:
    container_name: geth
    build:
      context: ./geth
      dockerfile: Dockerfile
    ports:
      - "8545:8545"
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ./geth/node:/geth
