version: "3.8"
services:

  geth:
    container_name: geth
    build:
      context: ./geth
      dockerfile: Dockerfile
    ports:
      - "8545:8545"
      - "8546:8546"
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ./geth/node:/geth

  nonce-manager:
    container_name: nonce-manager
    build:
      context: redis
      dockerfile: Dockerfile
    ports:
      - "6379:6379"
    environment:
      - TZ=Europe/Berlin

  tx-creation:
    container_name: tx-creation
    build:
      context: ./approach4/tx-creation
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - TZ=Europe/Berlin
      - PORT=8080
      - PRIVATE_KEY=bcc6d4aa1e277f085b3e11f2c1e6f14dd04e8108c823898e06fa5287c2bf1a92
      - NODE_URL=ws://geth:8546
      - CONTRACT_ADDRESS=0x17cB057648a03dE335c773C7F6b7719c63A32eB7
      - TX_INTERVAL=250
      - CONTINGENT_SIZE=100
      - REDIS_HOST=nonce-manager
      - REDIS_PORT=6379